name=input("enter your Name:")
branch=input("enter your Branch:")
gender=input("enter your Gender:")
college=input("enter your College name:")
age=int(input("enter your Age:"))
print("Name :",name)
print("Branch:",branch)
print("Gender:" ,gender)
print("College name :",college)
print("Age:",age)
